services:
  react-app:
    build:
      context: .
      target: dev # Sử dụng giai đoạn dev cho development với hot-reloading
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - WATCHPACK_POLLING=true
    command: npm start
